### ISSUE TITLE
Use of unauthenticated docker registry should be changed to authenticated 

### ISSUE THREAD

**Issue by SanjeevKGupta** [edgexfoundry-holding/orra#13]
This instruction makes user to install unauthenticated docker registry. 

https://github.com/edgexfoundry-holding/orra/tree/main/demos/OH-EXF-Jakarta#publish

This would open the hosted docker registry for access without any authentication from outside and anyone having access to the host IP address can push, pull images. This is a serious security hole. 

This needs to be fixed - either by making the docker registry Authenticated or remove this dependency.

**Comment by ajcasagrande** [comment]
The value of `LOCAL_DOCKER_REGISTRY` can be set to any docker registry, authenticated or unauthenticated. The instructions tell you how to run an unauthenticated one for ease of getting setup considering this is in the demos folder.

All of the images pushed there contain open source code (unless modified), and the Open Horizon agent tracks the SHA256 of the published images which reduces the concern for supply chain attacks there. I don't see this as a serious security hole, but I do agree we can add a warning to the users similar to how [Docker does](https://docs.docker.com/registry/deploying/):
> Warning
>
> These first few examples show registry configurations that are only appropriate for testing. A production-ready registry must be protected by TLS and should ideally use an access-control mechanism. Keep reading and then continue to the [configuration guide](https://docs.docker.com/registry/configuration/) to deploy a production-ready registry.
